"""Init migration

Revision ID: 0dd209205c41
Revises: 
Create Date: 2021-01-21 13:14:04.618254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd209205c41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=80), nullable=False),
    sa.Column('short_url', sa.String(length=4), nullable=False),
    sa.Column('death_date', sa.DateTime(), nullable=True),
    sa.Column('lifespan', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_url'),
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Links')
    # ### end Alembic commands ###
